### PR TITLE
fix: Allow to use environment executable java to launch servers

### LINKED ISSUE #1249: `JAVA_HOME` or `java.jdt.ls.java.home` should not be required for projects that don't develop Java code
Extension Name: vscode-gradle
Extension Version: v3.12.2
OS Version: RHEL8
VSCode version: 1.62.2

**Describe the bug**
The extension complains about not finding a setting for `JAVA_HOME` or `java.jdt.ls.java.home`, even when it's not being used to develop Java code. The extension seems to partially work, though. No language server is started, but Gradle tasks can be executed.

**To Reproduce**
Start VS Code with extension installed without installing Java extension, without setting a `JAVA_HOME` environment variable (but with `java` in `PATH`.

**Expected behavior**
I would expect the extension to fall back on the system location for `java`, which is on `PATH`, like Gradle itself does, and not require `JAVA_HOME` or the Java VS Code extension. I see from #249 that this is what the extension used to do.

**Screenshots**
image

**Output from "Gradle for Java"**
Log showing that the system installation for Java is being taken, but I'm guessing this comes from Gradle, not from VS Code.
```
[info] [gradle-server] Server started, listening on 43861
[info] Gradle client connected to server
[info] Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-2.el8_4.x86_64
[info] JVM Args: -XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
```

**Does the bug still exist if you disable all other extensions?**
Yes

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1249 

This pr checks and keeps the consistent of the two servers (Gradle server and Gradle language server), and follow Gradle behavior.

We will check the following ones (with descent priority), Beside VS Code configuration, we use step 4-5 to keep consistent with Gradle itself behavior.

1. config "java.import.gradle.java.home"
2. config "java.jdt.ls.java.home"
3. config "java.home" (deprecated)
4. environment JAVA_HOME
5. environment executable java(.exe)

### CODE REVIEW

File: extension/src/util/config.ts [hunk 1]
```diff
@@ -28,6 +29,19 @@ export function getConfigGradleJavaHome(): string | null {
     return getConfigJavaImportGradleJavaHome() || getJdtlsConfigJavaHome() || getConfigJavaHome();
 }
 
+export function getJavaHome(): string | undefined {
+    return getConfigGradleJavaHome() || process.env.JAVA_HOME;
+}
+
+export async function checkEnvJavaExecutable(): Promise<boolean> {
```
Comment (Eskibear) [inline extension/src/util/config.ts]: I don't see any async statements in the body.

File: extension/src/server/serverUtil.ts [hunk 2]
```diff
@@ -15,13 +15,15 @@ export interface ProcessEnv {
...
-    const javaHome = getConfigGradleJavaHome();
+export async function getGradleServerEnv(): Promise<ProcessEnv | undefined> {
+    const javaHome = getJavaHome();
     const env = { ...process.env };
     if (javaHome) {
         Object.assign(env, {
             VSCODE_JAVA_HOME: javaHome,
         });
+    } else if (!(await checkEnvJavaExecutable())) {
+        return undefined;
```
Comment (Eskibear) [inline extension/src/server/serverUtil.ts:26]: what will happen if `undefined` is returned? compared with previous behavior where `env` is returned.

Comment (Eskibear) [reply extension/src/server/serverUtil.ts:26]: prompt NO_JAVA_EXECUTABLE early before actually executing it?

File: extension/src/languageServer/languageServer.ts [hunk 3]
```diff
@@ -53,30 +54,24 @@ export async function startLanguageServer(
                 serverOptions = awaitServerConnection.bind(null, port);
             } else {
                 // keep consistent with gRPC server
-                const javaHome = getConfigGradleJavaHome() || process.env.JAVA_HOME;
+                const javaHome = getJavaHome();
+                let javaCommand;
                 if (!javaHome) {
```
Comment (Eskibear) [inline extension/src/languageServer/languageServer.ts]: Just 2 cents, flip the if-else branch would be more human-readable for me, because you don't assign a new `javaHome` in `if !javaHome` block..

Below makes more sense to me:

a) 
```
if (!javaHome) {
    javaHome = .....
    // do something requiring javaHome
} else {
    // do something requiring javaHome
}
```


b) 
```
if (javaHome) {
    // do something requiring javaHome
} else {
    // do something unrelated with javaHome
}
```

File: extension/src/server/serverUtil.ts (hunk 2 above)
Comment (CsCherrYY) [reply extension/src/server/serverUtil.ts:26]: > prompt NO_JAVA_EXECUTABLE early before actually executing it?

Yes. Please refer: https://github.com/microsoft/vscode-gradle/pull/1263/files#diff-3369ade313508c278005bfe83330cb8fb4852a75783f5f5843d8d89a46423fc6R43-R46, if we can't find a proper java executable, will return early.

The previous behavior is always to run the start script via `cmd` variable, in this way, Gradle will report an error if no java executable can be found.

File: extension/src/util/config.ts (hunk 1 above)
Comment (CsCherrYY) [reply extension/src/util/config.ts]: Let me remove "async" of this function and `getGradleServerEnv()`.

**Review by Eskibear — APPROVED** [review]
