### PR TITLE
fix: Run debuggable tasks always start debugging it

### LINKED ISSUE #1181: run debuggable tasks always start debugging it
Running a task that can be debugged will always trigger debug session, not just running it.

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1181 

create a new property ~`debugEnabled`~ `debuggable` in `GradleTaskDefinition`:

~`debugEnabled`~ `debuggable`: indicates the task can be debugged or not
`javaDebug`: indicates this run session of the task should be debugged or not

### CODE REVIEW

File: extension/src/tasks/taskUtil.ts [hunk 1]
```diff
@@ -234,9 +234,10 @@ function createVSCodeTaskFromGradleTask(
         rootProject: gradleTask.getRootproject(),
         projectFolder: rootProject.getProjectUri().fsPath,
         workspaceFolder: rootProject.getWorkspaceFolder().uri.fsPath,
+        debugEnabled: gradleTask.getDebuggable(),
```
Comment (Eskibear) [inline extension/src/tasks/taskUtil.ts]: why not simply call it 'debuggable' for consistency?

Comment (CsCherrYY) [reply extension/src/tasks/taskUtil.ts]: Good idea. Done in https://github.com/microsoft/vscode-gradle/pull/1183/commits/88b07386df1cb4caf019dd7950856924fdb4f546

**Review by Eskibear — APPROVED** [review]
