### PR TITLE
fix: Add gradle libraries to classpath

### LINKED ISSUE #1068: add all gradle library jars into groovy compiler's classpath

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1068 

here to automatically add gradle libraries into the classpath to support gradle default imports better.

### CODE REVIEW

File: gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java [hunk 1]
```diff
@@ -209,6 +217,8 @@ private File findLibFolder(DistInfo info) {
             // libFolder matches
             // .gradle/wrapper/dists/${gradleDist}/internal-string/${gradleVersion}/lib
             if (Utils.isValidFolder(libFolder)) {
+              this.gradleLibraryFolder = libFolder;
+              this.gradleFilesManager.setGradleLibraries(this);
```
Comment (testforstephen) [inline gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java]: why not to pass all gradle libraries to setGradleLibraries directly?

Comment (CsCherrYY) [reply gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java]: I'll change it.

**Review by testforstephen — APPROVED** [review]
