### PR TITLE
Fix for refreshing tasks

### LINKED ISSUE #12: Tasks are not refreshed until the treeview is expanded
We want the tasks refreshed when the extension is activated. The idea is to cache the tasks as early as possible so when you open the tasks view or run a task you don't need to wait for the tasks to be refreshed.

### PR DESCRIPTION
**Pull request by badsyntax**
Fixes https://github.com/badsyntax/vscode-gradle/issues/12

Previously we'd only get the tasks once the treeview was rendered. Now we explicitly refresh the tasks when the extension is activated.

### CODE REVIEW

File: src/gradleView.ts [hunk 1]
```diff
@@ -131,38 +131,34 @@ class NoTasksTreeItem extends TreeItem {
...
-  public refresh() {
+  refresh() {
     invalidateTasksCache();
     enableTaskDetection();
     this.taskTree = null;
-    this._onDidChangeTreeData.fire();
+    this.taskItemsPromise = tasks
+      .fetchTasks({ type: 'gradle' })
+      .then(taskItems => {
+        this._onDidChangeTreeData.fire();
```
Comment (badsyntax) [inline src/gradleView.ts]: We don't need to wait for this process to omplete before rerendering the tree, as the tree render will wait for this promise to complete

**Comment by badsyntax** [comment]
LGTM!
