### PR TITLE
fix: Update project after modifying build file

### LINKED ISSUE #1065: update project after modifying build file

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1065 

when the following events are watched
- change build file
- open build file

we trigger get projects process to update the classpath and closure infos of the given build file. we have a cache mechanism in https://github.com/microsoft/vscode-gradle/blob/6f051190b7273a2e747555aa100e09dbab4e80dc/extension/src/projectContent/GradleProjectContentProvider.ts#L18 so get project process from plugin will be triggered if
- A gradle file is opened at the first time
- A gradle file is changed.

### CODE REVIEW

File: extension/src/Extension.ts [hunk 1]
```diff
@@ -315,8 +317,13 @@ export class Extension {
   private handleWatchEvents(): void {
     this.buildFileWatcher.onDidChange(async (uri: vscode.Uri) => {
       logger.info('Build file changed:', uri.fsPath);
+      void this.syncBuildFile(uri);
```
Comment (testforstephen) [inline extension/src/Extension.ts]: The cache will be hit and return an old project content to language server. 
But on file save, the cache actually should expire and refetch project content, right?

Comment (CsCherrYY) [reply extension/src/Extension.ts]: Yes. Currently we have https://github.com/microsoft/vscode-gradle/blob/6f051190b7273a2e747555aa100e09dbab4e80dc/extension/src/Extension.ts#L318 here to refresh all the caches including project content caches. I'll change this `syncBuildFile()` to after the `refresh()` to let's sync with the new content.

Comment (CsCherrYY) [reply extension/src/Extension.ts]: reference: https://github.com/microsoft/vscode-gradle/blob/6f051190b7273a2e747555aa100e09dbab4e80dc/extension/src/commands/RefreshCommand.ts#L23

**Review by testforstephen — APPROVED** [review]
