### PR TITLE
fix: Open a new gradle project in VS Code and code completion won't work

### LINKED ISSUE #1018: Open a new gradle project in VS Code and code completion won't work
Use VS Code to open a new gradle project, whose gradle distribution is not cached in local machine before. Once the gradle extension is ready, and try code completion, no suggestions come up.

The workaround is to reload VS Code window.

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1018

### CODE REVIEW

File: gradle-language-server/src/main/java/com/microsoft/gradle/GradleServices.java [hunk 1]
```diff
@@ -83,7 +83,7 @@
 
 public class GradleServices implements TextDocumentService, WorkspaceService, LanguageClientAware {
 
-  public static final List<String> supportedCommands = List.of("gradle.getDependencies");
+  public static final List<String> supportedCommands = List.of("gradle.getDependencies", "gradle.wrapperChanged");
```
Comment (testforstephen) [inline gradle-language-server/src/main/java/com/microsoft/gradle/GradleServices.java]: Use a more generic name for the new command, such as `"gradle.distributionChanged"`?

File: gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java [hunk 2]
```diff
@@ -77,31 +79,33 @@ public void setWorkspacePath(Path workspacePath) {
     return this.javaConfigurations;
   }
 
-  public void resolve() {
+  public boolean resolveLibFiles() {
```
Comment (testforstephen) [inline gradle-language-server/src/main/java/com/microsoft/gradle/resolver/GradleLibraryResolver.java]: resolveAPIJar

File: gradle-language-server/src/main/java/com/microsoft/gradle/GradleServices.java (hunk 1 above)
Comment (CsCherrYY) [reply gradle-language-server/src/main/java/com/microsoft/gradle/GradleServices.java]: This command will be triggered only when the `gradle-wrapper.properties` changes. If the related setting changes, we use `didChangeConfiguration` to handle.

**Review by testforstephen — APPROVED** [review]
