### PR TITLE
fix: Extension generates project with errors

### LINKED ISSUE #1170: The extension generates project with errors
Extension Name: vscode-gradle
Extension Version: 3.10.0
OS Version: Arch Linux x86_64
VSCode version: 1.63.2

**Describe the bug**
When I create project via this extension with the name my-project (or something like that, but not com.project.my) it generates wrong folder hierarchy and package name inside App.java file

**To Reproduce**
1. Execute "Java: Create Java project..." command
2. Select Gradle from the dropdown
3. Create a folder "my-project"
4. Select it as target folder
5. Select Groovy as build script DSL
6. Leave project name unchanged

**Expected behavior**
The expected behavior is the same as when I type `gradle init` and follow all the steps (the project name is the same, my-project). This way the project is generated correctly.

**Screenshots**
By Using the extension
image

`gradle init`
image

**Output from "Gradle for Java"**
[info] [gradle-server] Server started, listening on 44129
[info] Gradle client connected to server

**Does the bug still exist if you disable all other extensions?**
Yes

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1170 

Now we will check & suggest the package name when creating a new Gradle project.

- In simple mode, the package name will be automatically normalized.
- In advanced mode, during specific package name step, the default name will be normalized:
image
the default package name is normalized from `cs-proj`(the folder name) to `cs.proj`
- when you try to use an invalid name, the inputbox will be disabled and show error message and suggestion.
image

### CODE REVIEW

File: gradle-server/src/main/java/com/github/badsyntax/gradle/utils/Utils.java [hunk 1]
```diff
@@ -39,4 +40,31 @@ private static Version getLowestGradleVersion(Version javaVersion) {
 		}
 		return new Version("2.0");
 	}
+
+	public static String normalizePackageName(String name) {
```
Comment (CsCherrYY) [inline gradle-server/src/main/java/com/github/badsyntax/gradle/utils/Utils.java:44]: see reference: https://github.com/gradle/gradle/blob/c05ebe28735e1cb052db9d275a9687290b04c80b/subprojects/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java#L287 and https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/PackageNameBuilder.java#L20

We can't directly use this util method since it will bring a dependency on Gradle itself. It will increase 150MB size into the current package.

Comment (Eskibear) [reply gradle-server/src/main/java/com/github/badsyntax/gradle/utils/Utils.java:44]: makes sense.

**Review by Eskibear — APPROVED** [review]

**Comment by CsCherrYY** [comment]
verify steps:

Advanced mode
1. new a folder and its name include a specific character. e.g., "test-folder"
2. execute `Gradle: Create a Gradle Java Project... (Advanced)`
3. select the new folder
4. select "application", DSL, test framework and project name,
5. in specify package name step, you can see the default package name is normalized. e.g., "test.folder"
6. generate the project, and you can find the generated project package name is the normalized name.

simple mode
1. new a folder and its name include a specific character. e.g., "test-folder"
2. execute `Java: Create Java Project...`
3. select Gradle project, and the new folder
4. select DSL and project name
5. generate the project, and you can find the generated project package name is the normalized name. e.g., "test.folder"

**Comment by Eskibear** [comment]
Adv mode, step 5. Package name validation is NOT real-time! 

- I changed it to `test-folder`, no error
- press `enter`, error occurred
- change back to `test.folder`, error was still there, as below

image

**Comment by CsCherrYY** [comment]
> Adv mode, step 5. Package name validation is NOT real-time!
> 
> * I changed it to `test-folder`, no error
> * press `enter`, error occurred
> * change back to `test.folder`, error was still there, as below
> 
> image

It's by design. The verification is done at the server side, so if we do it real-time, there will be too many requests to the server. Here I just send a request when you press enter key.

Or do you think we'd be better showing this message only once? After you press any character, the message will disappear.

**Comment by Eskibear** [comment]
I prefer real-time validation. Performance issue might be mitigated by debouncing?

**Comment by CsCherrYY** [comment]
> I prefer real-time validation. Performance issue might be mitigated by debouncing?

Yeah, I'll have a try.
