### PR TITLE
fix: GradleServer won't exit when the extension exits

### LINKED ISSUE #1184: GradleServer won't exit when the extension exits
now when you exit or uninstall the extension, the GradleServer process is still running in the background, causing the waste of resources and occupying.

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1184 

the current dispose mechanism in vscode for extension is synchronous, making it hard to finish the disposing process, see https://github.com/microsoft/vscode/issues/140697#issuecomment-1017559485. An alternative way is to put the process into async `deactivate` function.

### CODE REVIEW

File: extension/src/index.ts [hunk 1]
```diff
@@ -24,4 +27,6 @@ function initializeTelemetry(): void {
 }
 
 // eslint-disable-next-line @typescript-eslint/no-empty-function
-export function deactivate(): void {}
+export async function deactivate(): Promise<void> {
+    await extension?.deactivate();
```
Comment (Eskibear) [inline extension/src/index.ts]: infinite loop?

Comment (CsCherrYY) [reply extension/src/index.ts]: here is calling function `deactivate()` from an instance of **Extension**, which will be initialized in function `activate()`

**Review by Eskibear — APPROVED** [review]
