### PR TITLE
fix: Can't handle gradle version scheme like 7.3-rc-2

### LINKED ISSUE #1049: can't handle gradle version scheme like `7.3-rc-2`
in gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-rc-2-bin.zip
```
in Java Debug Console:
```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7cafb7c8
java.lang.NumberFormatException: For input string: "3-rc-2"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.github.badsyntax.gradle.handlers.GetBuildHandler.createVersion(GetBuildHandler.java:170)
        at com.github.badsyntax.gradle.handlers.GetBuildHandler.getHighestJDKVersion(GetBuildHandler.java:138)
        at com.github.badsyntax.gradle.handlers.GetBuildHandler.run(GetBuildHandler.java:103)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by CsCherrYY**
fix #1049

### CODE REVIEW

**Review by Eskibear — DISMISSED** [review]
BTW have you setup unit test to guard this?

File: gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java [hunk 1]
```diff
@@ -135,40 +135,27 @@ private String getRootCause(Throwable error) {
...
+    } else if (gradleVer.isLowerThan("6.0.0")) {
+      return new Version("12.0.0");
+    } else if (gradleVer.isLowerThan("6.3.0")) {
+      return new Version("13.0.0");
+    } else if (gradleVer.isLowerThan("6.7.0")) {
+      return new Version("14.0.0");
+    } else if (gradleVer.isLowerThan("7.0.0")) {
+      return new Version("15.0.0");
     }
+    return new Version("16.0.0");
```
Comment (mozhuanzuojing) [inline gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java]: > Gralde since 7.0 version supports JDK16, and JDK17 will be supported soon in 7.3 version.

- The following code should be added
```java

else if (gradleVer.isLowerThan("7.3.0")) {
  return new Version("16.0.0");
}
return new Version("17.0.0");
```

Comment (CsCherrYY) [reply gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java]: @mozhuanzuojing FYI, this mechanism is used to help the user to know if the current error is caused by compatibility issue. If your build doesn't have any error, this compatibility table will not affect anything. Here we just keep the compatibility table consistent with https://docs.gradle.org/current/userguide/compatibility.html. Could you post the reference (any url of Gradle official page) about your attached info?

**Comment by CsCherrYY** [comment]
> BTW have you setup unit test to guard this?

Yes. I plan to add tests about this (and other ls features) in the near feature. Here we have https://github.com/microsoft/vscode-gradle/issues/1042 to track.

File: gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java (hunk 1 above)
Comment (mozhuanzuojing) [reply gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java]: @CsCherrYY  please read https://docs.gradle.org/7.3-rc-3/release-notes.html#java17.

Comment (CsCherrYY) [reply gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java]: Get it. Let's add Java 17 information into the current table. Thank you!

**Review by testforstephen — APPROVED** [review]
