### PR TITLE
fix: Task execution terminal always shows error

### LINKED ISSUE #936: Run Task should reuse the terminal
https://user-images.githubusercontent.com/14052197/130403167-fcf949b0-49e1-4aaa-af28-69b71b3806fa.mov

Currently it just kills the old terminal and then creates a new terminal. Can we change it to reuse the existing terminal?

### PR DESCRIPTION
**Pull request by CsCherrYY**
Currently, the task execution terminal will always show error after the task executed, although there is no error when running this task.
task
This PR will fix the bug. The root cause can be found here: https://github.com/microsoft/vscode/issues/125725

Besides, this PR uses `vscode.TaskPanelKind` to control terminal behavior, which also fix #936

### CODE REVIEW

File: extension/src/terminal/GradleRunnerTerminal.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ export class GradleRunnerTerminal implements vscode.Pseudoterminal {
     } catch (e) {
       this.handleError(e);
```
Comment (testforstephen) [inline extension/src/terminal/GradleRunnerTerminal.ts:110]: In normal workflow,  `this.closeEmitter.fire(0);`.
In catch hander, `this.closeEmitter.fire(1);`

**Review by testforstephen — DISMISSED** [review]

**Review by testforstephen — APPROVED** [review]
