### PR TITLE
Fix: Task Server jdk search compatibility check

### LINKED ISSUE #1546: Version 3.16.0 does not work any more
Extension Name: vscode-gradle
Extension Version: 3.16.0
OS Version: Windows
VSCode version: 1.91.1
JAVA_HOME: C:\Program Files\java\openjdk-11

**Describe the bug**
When I start VSCode the following 2 errors pop up:

- No connection to gradle server. Try restarting the server.
- The Gradle client was unable to connect. Try re-connecting.

But reloading did not help. A also tried a new installation and deleted the ~/.vscode and ~/AppData/Roaming/Code folder

**To Reproduce**
This happens on my computer, with the following files:
- .vscode/settings.json file

```
{
    "java.compile.nullAnalysis.mode": "automatic",
    "java.import.gradle.java.home": "/C/Program Files/java/openjdk-8",
    "java.configuration.updateBuildConfiguration": "interactive",
}
```
- test\gradlew 
- test\gradlew.bat 
- test\build.gradle
```
apply plugin: 'java'
```
- test\gradle\wrapper\gradle-wrapper.properties (version gradle-5.2.1-bin.zip)
- test\gradle\wrapper\gradle-wrapper.jar

**Expected behavior**
This should work as in version 3.15.0

**Screenshots**
No screenshots

**Output from "Gradle for Java"**
[info] [gradle-server] ERROR: JAVA_HOME is set to an invalid directory: /C/Program Files/java/openjdk-8
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
[warn] [gradle-server] Gradle server stopped
[error] Error connecting to gradle server: The channel has been closed
[error] The client has state: SHUTDOWN

**Does the bug still exist if you disable all other extensions?**
Moving to the previous version 3.15.0 helps (as a workarround)

**Additional context**
I have to continue with these old version gradle 5, java 8

### PR DESCRIPTION
**Pull request by Jiaaming**
should fix: https://github.com/microsoft/vscode-gradle/issues/1546

### CODE REVIEW

File: extension/src/util/config.ts [hunk 1]
```diff
@@ -29,6 +29,17 @@ export function getConfigJavaImportGradleJavaHome(): string | null {
     return vscode.workspace.getConfiguration("java").get<string | null>("import.gradle.java.home", null);
 }
 
+export async function getNeededConfigJavaImportGradleJavaHome(requiredJdkVersion: number): Promise<string | null> {
```
Comment (jdneo) [inline extension/src/util/config.ts]: getConfigJavaImportGradleJavaHomeIfHigherThan()

**Review by jdneo — APPROVED** [review]
